### ISSUE TITLE
[Bug]: Very big problem with the local translation cache

### ISSUE THREAD

**Issue by iG8R** [immersive-translate/immersive-translate#3327]
### 插件版本号 | Version

1.21.2

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

Hi.
Sorry to bother, but the following problems are really driving me crazy.
1. Recently, every now and then, some problems arise with the providers' servers, for example, the server responds as follows `[{"index":0,"message":{"role":"assistant","content":"","reasoning":null,"tool_calls":null,"audio":null},"finish_reason":"stop"}]`, and IM gets an empty response, which made it link original text with nothing.
For example:

<img width="2466" height="1388" alt="Image" src="https://github.com/user-attachments/assets/0fa304dd-c74a-4274-a08c-b6b60b0a2f26" />

<img width="2466" height="1388" alt="Image" src="https://github.com/user-attachments/assets/55ed316b-fd9f-446b-8b50-023e23de0a0c" />

It leads to the situation, when if I want to "renew" these empty translations, the only possible solution I found is clearing the cache via `Options -> General -> Clear cache` or `Options -> About -> Clear cache`.
Thus, all previous "good" cache is also erased.

**Please, could it be possible to implement such functionality that checks whether the caching response is empty and does not save it in the cache.**

2. The second issue is interconnected with the the first one. IM retains entries of all previously erased cached links in the Local storage `cache_list`.
The following is what is actually used by IM for the time being:

<img width="2465" height="3149" alt="Image" src="https://github.com/user-attachments/assets/2da6e005-c6bb-417f-804c-caa42c21614b" />

And the next is what is stored in the `cache_list` entry, and in the screenshot I don't shot all the entries, only the beginning, because the process of their listing is so time consuming that I cannot wait that long, and during this process my system went to a frozen state with 100% CPU usage.

<img width="2465" height="8569" alt="Image" src="https://github.com/user-attachments/assets/2e099879-1ea0-48f2-af57-7e912c99dd4f" />

Neither `Options -> General -> Clear cache` nor `Options -> About -> Clear cache` help in this situation.
The only solution I've found is to completely uninstall IM, restart Firefox, then reinstall IM - only after all these steps `cache_list` will be purged and not freeze my system during `Options -> About -> Clear cache`.

**Could it be possible to fix this problem as well?**

**Comment by keyboard3** [comment]
The caching issue with empty responses has been resolved.

The lagging problem when clearing the cache cannot be reproduced. If you've just installed the plugin and only have a few KB of cache, does clearing it also cause lag?

**Comment by iG8R** [comment]
Thank you very much!

> The lagging problem when clearing the cache cannot be reproduced. If you've just installed the plugin and only have a few KB of cache, does clearing it also cause lag?

That's the thing, when I just installed IM and only have a few KB of cache, the clearing is very fast, but over time, when `cache_list` amasses all that garbage entries, this issue starts stand tall and significantly affects the use of IM and the entire system.

**Comment by keyboard3** [comment]
Got it, we'll observe Firefox's clearing performance when the plugin cache is relatively large

**Comment by iG8R** [comment]
@keyboard3 

Unfortunately, the problem pertaining to the linkage of the original text with nothing still persists:

<img width="2464" height="1382" alt="Image" src="https://github.com/user-attachments/assets/5404220f-f5bf-418e-ba53-b507b0f390ab" />

<img width="1920" height="13593" alt="Image" src="https://github.com/user-attachments/assets/84ca5a0c-42e8-4b4d-8419-6bd71bf53325" />

<img width="1920" height="7471" alt="Image" src="https://github.com/user-attachments/assets/c2a2b7cc-1f79-4fc4-9129-97430698e68d" />

**Comment by keyboard3** [comment]
Are you clear about the cache? An empty response means empty content

**Comment by iG8R** [comment]
I am not sure about IM's internal processes and how it interprets empty content, but I see what is happening inside the provider server itself and what it responds. Sometimes the server, due to issues with itself, responds `[{"index":0,"message":"role":"assistant","content":"","reasoning":null,"tool_calls":null,"audio":null},"finish_reason":"stop"}]`, and this is why IM associates the original text paragraph with emptiness, creating a situation where this original text paragraph corresponds to empty content. But in reality, it was just a temporary problem with the provider server. Nevertheless, IM continues to use this erroneous binding permanently until the user is forced to clear the cache, losing all other "good" cached paragraphs in the process.
Logically, if there is no "empty" paragraph in the source text, then the IM should not associate it with emptiness - either not associate it at all, or make a new request to get the translated paragraph.
Unfortunately, this problem occurs sporadically and without any dependencies, so it is very difficult to reproduce, but I can show how the provider server works.

![Image](https://github.com/user-attachments/assets/fef62420-cb22-47d6-b1b9-687d2058e64c)

**Comment by keyboard3** [comment]
1.21.5 fix empty cache issue

**Comment by iG8R** [comment]
@keyboard3 
Thank you very much!

While waiting for a version update, here is how the cache clearance behave when `cache_list` has accumulated garbage entries.

https://github.com/user-attachments/assets/6480130f-8089-43cc-b04c-b8f4807229d1

**Comment by iG8R** [comment]
@keyboard3 
> 1.21.5 fix empty cache issue

It seems this didn't work as intended, and, IMHO, it got worse, as the number of empty entries even increased.
Here is the screencast, some parts I sped up to save time.

https://github.com/user-attachments/assets/b8121da9-51b6-44f0-919e-65dcba1249f7

**Comment by keyboard3** [comment]
Both read and write caches have been checked to determine whether the translated content is empty. If the cached translation is empty, it won't be read from the cache, and if the response is empty, it won't be written to the cache

**Comment by keyboard3** [comment]
I can't reproduce the issue you mentioned. You'd better package and download the requests from the settings page to help us reproduce the problem

<img width="791" height="298" alt="Image" src="https://github.com/user-attachments/assets/a32028e3-2c48-414a-9a90-809b739ca01b" />

**Comment by iG8R** [comment]
Thank you for your efforts!
At the moment, I've already cleared the cache, as soon as this issue arises again, I'll proceed as you suggested.

**Comment by iG8R** [comment]
@keyboard3 
There is definitely something wrong with how the IM cache works in Firefox (about other browsers I don't know, as I don't use them).
Here is a screencast in which I tried to do as you suggested and figure out why IM still assigns an empty response to the source text, but... I couldn't finish it because devtools stopped responding. I waited for almost 15 minutes, but to no avail.
PS. I sped up the second part of the video because waiting for a response from the devtools window took too much time.
PPS. Here is the page where I encountered this issue, but, essentially, it could have happened on any page.
https://www.piaotia.com/html/6/6470/3943275.html

https://github.com/user-attachments/assets/5ce6f534-e705-4d1e-a67f-ed8312ec3d0d

**Comment by iG8R** [comment]
Finally, I've caught it. I constantly forgot to open the IM's DevTools window, before getting such strange behavior with incorrect positioning and missing translations.

[devtools_Archive \[25-10-02 23-28-41\]-01.zip](https://github.com/user-attachments/files/22678924/devtools_Archive.25-10-02.23-28-41.-01.zip)

https://www.piaotia.com/html/6/6470/3976860.html

<img width="960" height="1462" alt="Image" src="https://github.com/user-attachments/assets/d5093471-b0d4-4bad-9392-735f766a867f" />
